# 지킬에 오신 것을 환영합니다!
#
# 이 설정 파일은 전체 블로그에 영향을 미치는 설정, 값에 대한 것입니다.
# 한 번만 설정하고 그 이후에는 거의 수정하지 않는 것이 좋습니다. 이 파일을 자주 수정하는 경우
# 이 파일을 자주 편집하는 경우, 필요한 데이터에 대해 지킬의 데이터 파일
# 자주 업데이트해야 하는 데이터에는 지킬의 데이터 파일 기능을 사용하세요.
#
# 기술적인 이유로 이 파일은 다음을 사용할 때 자동으로 다시 로드되지 않습니다.
# 'bundle exec jekyll serve'. 이 파일을 변경하는 경우 서버 프로세스를 다시 시작하세요.

# 사이트 설정
# 새 사이트를 개인화하는 데 사용됩니다. HTML 파일을 보면
# {{ site.title }}, {{ site.email }} 등을 통해 액세스하는 것을 볼 수 있습니다.
# 원하는 사용자 정의 변수를 만들 수 있으며,
# 템플릿에서 {{ site.myvariable }}를 통해 템플릿에서 액세스할 수 있습니다.
logo: "/assets/favicon/android-chrome-512x512.png"
title: ENVY BROS.
email: devenvy100@gmail.com
description: >- # "baseurl:"까지 줄 바꿈을 무시한다는 의미입니다.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: pulp-pixel
minimal_mistakes_skin: dark
repository: "envybros/website"
search: true
future: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "펄프픽셀"

  avatar: "/assets/images/avatar.svg"
  bio: "온갖 컴공 지식을 번역 및 공유합니다."
  links:
    - label: "Linktree"
      icon: "fas fa-fw fa-tree"
      url: "https://linktr.ee/envybros"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/envybros"
    - label: "Blog"
      icon: "fab fa fa-heart"
      url: "https://blog.naver.com/devenvyy"

footer:
  links:
    - label: "Linktree"
      icon: "fas fa-fw fa-tree"
      url: "https://linktr.ee/envybros"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/envybros"
    - label: "Blog"
      icon: "fab fa fa-heart"
      url: "https://blog.naver.com/devenvyy"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      # read_time: false
      comments: true
      # share: true
      # related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      # author_profile: true
comments:
  provider: "giscus"
  giscus:
    #    repo_id              : "envybros/website" # Shown during giscus setup at https://giscus.app
    #    category_name        : "docs" # Full text name of the category
    #    category_id          : # Shown during giscus setup at https://giscus.app
    #    discussion_term      : "docs" # "pathname" (default), "url", "title", "og:title"
    #    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    #    theme                : "Github Dark" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    repo: "envybros/website"
    repo_id: "R_kgDOJW6miA"
    category: "General"
    category_id: "DIC_kwDOJW6miM4CVyws"
    mapping: "pathname"
    strict: "0"
    reactions-enabled: "1"
    emit-metadata: "1"
    input-position: "top"
    theme: "dark"
    lang: "ko"
    crossorigin: "anonymous"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
